[package]
name = "select_indices"
description = "Iterators for taking multiple shared/exclusive references from a slice"
categories = ["rust-patterns", "concurrency"]
keywords = ["indices", "slice", "split", "rayon"]
authors = ["TGRCDev"]
version = "0.2.2"
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/TGRCdev/select_indices"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = { version = "^1", optional = true }